# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."tunarr" = {
    image = "chrisbenincasa/tunarr:latest";
    environment = {
      "LOG_LEVEL" = "INFO";
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "/var/lib/tunarr:/config/tunarr:rw"
      "/media/storage/media/:/media:rw"
    ];
    ports = [
      "5444:8000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=tunarr"
      "--network=tunarr_default"
    ];
  };
  systemd.services."docker-tunarr" = {
    unitConfig = {
      RequiresMountsFor = [ "/media" ];
      After = [ "media.mount" ];
      Wants = [ "media.mount" ];
    };
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-tunarr_default.service"
    ];
    requires = [
      "docker-network-tunarr_default.service"
    ];
    partOf = [
      "docker-compose-tunarr-root.target"
    ];
    wantedBy = [
      "docker-compose-tunarr-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-tunarr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f tunarr_default";
    };
    script = ''
      docker network inspect tunarr_default || docker network create tunarr_default
    '';
    partOf = [ "docker-compose-tunarr-root.target" ];
    wantedBy = [ "docker-compose-tunarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-tunarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
